name: Payments Service CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format

      - name: Build application
        run: npm run build

      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            # Load NVM if it exists
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # If NVM isn't installed, install it
            if ! command -v nvm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi

            # Install and use Node.js 18
            nvm install 18
            nvm use 18

            # Install PM2 globally if not present
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Navigate to project directory and deploy
            cd /home/administrator/lattelink/payments-subscriptions-microservice || exit 1
            git pull origin master || exit 1
            npm ci || exit 1
            npm run build || exit 1
            pm2 reload payments-service || pm2 start dist/main.js --name "payments-service" --time
